app/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime
from flask_login import UserMixin
from . import login_manager

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class Random:
    '''
    Random class to define Random Quotes oblects
    '''
    def __init__(self, author, quote):
        self.author = author
        self.quote = quote

class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(255), index = True)
    email = db.Column(db.String(255), unique = True, index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pass_secure  = db.Column(db.String(255))

    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'User {self.username}'

class Blog(db.Model):
    __tablename__ = 'blogs'

    id = db.Column(db.Integer, primary_key = True)
    title = db.Column(db.String(255))
    content = db.Column(db.String)
    posted = db.Column(db.DateTime, default = datetime.utcnow)
    comment = db.relationship('Comment', backref = 'blog', lazy = 'dynamic')

    def save_blog(self):
        db.session.add(self)
        db.session.commit()

    def _repr_(self):
        return f'Blog {self.title}'

class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key = True)
    comment = db.Column(db.String(255))
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    blog_id = db.Column(db.Integer, db.ForeignKey('blogs.id'))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls, blog_id):
        comments = Comment.query.filter_by(blog_id = blog_id).all()

        return comments

    def __repr__(self):
        return f'comment:{self.comment}' 

app/models/random.py
class Random:
    '''
    Random class to define Random Quotes oblects
    '''
    def __init__(self, author, quote):
        self.author = author
        self.quote = quote

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import InputRequired

class CommentForm(FlaskForm):
    comment = TextAreaField('Your comment here', validators=[InputRequired()])
    submit = SubmitField('Post')

class BlogForm(FlaskForm):
    title = StringField('Blog title', validators=[InputRequired()])
    content = TextAreaField('Say something', validators=[InputRequired()])
    submit = SubmitField('Submit')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.', validators=[InputRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_optins
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet, configure_uploads, IMAGES

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos', IMAGES)

def create_app(config_name):
    #Initializing application
    app = Flask(__name__)

    #Setting up configuration
    app.config.from_object(config_optins[config_name])

    #Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    #Registering the blueprints
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint)

    #Configure uploadset
    configure_uploads(app, photos)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, error

app/main/views.py
from flask import render_template, request, redirect, url_for, abort
from . import main
from ..request import get_quotes
from ..models import Blog, User, Comment
from .forms import BlogForm, CommentForm, UpdateProfile
from flask_login import login_required
from .. import db, photos

#Views
@main.route('/')
def index():
    '''
    View root page function that returns the index page and its data
    '''
    random_quotes = get_quotes()
    print(random_quotes)
    blogs = Blog.query.all()
    user = User.query.all()
    title = "Bloggr"
    return render_template('index.html', title = title, random = random_quotes, blogs = blogs, user = user)

@main.route('/create_new', methods = ["GET", "POST"])
@login_required
def new_blog():
    form = BlogForm()

    if form.validate_on_submit():
        title  = form.title.data
        content = form.content.data

        new_blog = Blog(title = title, content = content)
        db.session.add(new_blog)
        db.session.commit()
        return redirect(url_for('main.index'))
    else:
        all_blogs = Blog.query.order_by(Blog.posted)

    return render_template('new_blog.html', blog_form = form, blogs = all_blogs)
        

@main.route('/comment/<int:blog_id>', methods = ["GET", "POST"])
@login_required
def comment(blog_id):
    form = CommentForm()
    blog = Blog.query.get(blog_id)
    all_comments = Comment.query.filter_by(blog_id = blog_id).all()
    
    if form.validate_on_submit():
        comment = form.comment.data
        blog_id = blog_id
        new_comment = Comment(comment = comment, blog_id = blog_id)
        db.session.add(new_comment)
        db.session.commit()
        return redirect(url_for('.comment', blog_id = blog_id))
    
    return render_template('new_comment.html', comment_form = form, blog = blog, all_comments = all_comments)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update', methods = ["GET", "POST"])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile', uname = user.username))

@main.route('/user/<uname>/update/pic', methods = ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()

    return redirect(url_for('main.profile', uname = uname))

app/views.py
from flask import render_template
from app import app
from .request import get_quotes

#Views
@app.route('/')
def index():
    '''
    View root page function that returns the index page and its data
    '''
    random_quotes = get_quotes()
    print(random_quotes)
    title = "Blog"
    return render_template('index.html', title = title, random = random_quotes)

app/templates/base.html
{% extends 'bootstrap/base.html' %}

<!-- Navbar block -->
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}

<!-- Content block -->
{% block content %}
<div class="container">
    <h2 class="text-center">Your Random Quote For Today</h2>
    <p class="text-center"><em>{{random.quote}}</em></p>
    <p class = "text-center"><strong>{{random.author}}</strong></p>
    <br>
    <br>
    {% for blog in blogs %}
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
              <h3><strong>{{blog.title}}</strong></h3>
            </div>
            <div class="card-body">
              <blockquote class="blockquote mb-0">
                <p>{{blog.content}}</p>
                <footer class="blockquote-footer">Posted on {{blog.posted}}</footer>
                <a class="btn btn-primary" href="{{url_for('main.comment', blog_id = blog.id)}}">Comments:{{blog.comment.count()}}</a>
              </blockquote>
            </div>
          </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

app/templates/navbar.html
<div class="navbar navbar-inverse" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Bloggr</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/">Home</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li style="color:white;"><a href="{{url_for('main.profile',uname = current_user.username)}}">Profile</a></li>
                <li><button style="margin-top: 8px;" class="btn btn-info"><a href="{{url_for('main.new_blog')}}">Create Blog</a></button></li>
                <li><a href="{{url_for('auth.logout')}}">Sign out</a></li>
                {% else %}
                <li><a href="{{url_for('auth.login')}}">Sign in</a></li>
                {% endif %}
            </ul>
        </div>

    </div>
</div>

app/templates/new_blog.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    <div class="col-md-4">
        {{wtf.quick_form(blog_form)}}
    </div>
</div>
{% endblock %}

app/templates/new_comment.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    <div class="col-md-8">
        {{wtf.quick_form(comment_form)}}
    </div>
    <br>
    <br>
    <h3 class="text-centre">Blog Comments</h3>
    {% for comment in all_comments %}
        <div class="col-md-12">
            <ul>
                <li>{{comment.comment}}</li>
                <li></li>
            </ul>
        </div>
    {% endfor %}
</div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <!-- Displaying username -->
        <div class="col-md-4">
            <h3> {{user.username|capitalize}} </h3>

            <!-- Displaying user bio -->
            {% if user.bio %}
                <p> {{user.bio}} </p>
            {% else %}
                <p> {{user.username|capitalize}} has no bio</p>
            {% endif %}
        </div>

        <!-- Displaying profile photo -->
        <div class="col-md-4">
            {% if user.profile_pic_path %}
                <img src="{{url_for('static', filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
            {% else %}
                <p>No profile picture</p>
            {% endif %}

            {% if user == current_user %}
                <form action="{{url_for('main.update_pic', uname = user.username)}}" method = "post" enctype = "multipart/form-data">
                    <input type="file" name="photo" class="form-control" required>
                    <input type="submit">
                </form>
            {% endif %}
        </div>
        <div class="col-md-4">
            {% if user == current_user %}
                <a href="{{url_for('main.update_profile', uname = user.username)}}">Edit Profile</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    {{wtf.quick_form(form)}}
</div>
{% endblock %}